### ISSUE TITLE
Convenience: Allow start/end to be given as year-integers

### ISSUE THREAD

**Issue by zauster** [ropensci/comtradr#10]
Hey,

i use always annual data (and it's also the default value). So it would be convenient to let the user specify only `start = 2005` or `end = 2005` if `freq = "annual"`. `start = 2005` would expand to `2005-01-01` and `end = 2005` to `2005-12-31`.
What do you think of that?

**Comment by ChrisMuir** [comment]
I like this idea, thanks for the suggestion! I may have some time this week to do this, otherwise this weekend.

Thanks again!

**Comment by ChrisMuir** [comment]
Just pushed this feature.

Now, when arg `freq` is set to `"annual"`, these inputs for both `start_date` and `end_date` would all be valid: `"2016-01-01"`, `"2016"`, and `2016`.

When arg `freq` is set to `"monthly"`, these inputs for bot `start_date` and `end_date` would all be valid: `"2016-01-01"` and `"2016-01"`.

Thanks again for suggesting this feature @zauster!
