### ISSUE TITLE
API planned updates/upgrades for 2018

### ISSUE THREAD

**Issue by ChrisMuir** [ropensci/comtradr#13]
Per the United Nations Comtrade [website](https://comtrade.un.org/data/doc/UpgradePlan), they are planning to make a bunch of updates and upgrades to their API service, which will coincide with a version change (from v.1 to v.2). Looks like they expect v.2 to be made available sometime mid-year 2018, and for v.1 to be discontinued at the end of 2018. So as soon as v.2 is publicly available, I will be working on updating this package to reflect the new features.

Below is a list of planned changes from their [Upgrade Plan](https://comtrade.un.org/data/doc/UpgradePlan) website. This will be a fair amount of work 😸 

EDIT: As of 2018-11-10, the [Upgrade Plan](https://comtrade.un.org/data/doc/UpgradePlan) website indicates that there have been delays in rolling this out....looks like it may not happen until 2019.

Previous System | Upgrades made with new system | Result for Comtrade Users
-- | -- | --
Three separate processing systems for annual and monthly Merchandise Trade Statistics and Trade in Services | One integrated processing system for all trade data | Improved consistency and timeliness of dissemination of trade data. Monthly Merchandise Trade Statistics will be disseminated the same way as annual Merchandise Trade Statistics data (e.g., will be converted to other classifications and missing quantities will be estimated)
Data items for Merchandise Trade Statistics included trade by commodity and by partner | In addition, new data items now include (when reported):mode of transportcustoms procedure codes2nd partner | More information on the nature of trade flows and partner country attribution, allowing for better analysis of bilateral trade asymmetries
Single valuation for Merchandise Trade Statistics imports (at CIF) and exports (at FOB) | In addition, FOB valuation for imports (when reported) | Symmetrical valuation of imports and exports and more information on insurance and freight costs, allowing for better analysis of bilateral trade asymmetries
Trade flows for Merchandise Trade Statistics consisted of Total Exports: Re-exports; Total Imports; and Re-Imports | Expanded breakdown of trade flows for Merchandise Trade Statistics (when reported) including Domestic Exports, Export/Import of goods after/for inward processing; Export/Import of goods for/after outward processing; and Export/Import on intra-firm trade | More information on the nature of trade flows, especially re-exports, re-imports, and goods for processing, and intra-firm trade
Merchandise Trade Statistics quantity units standardised to 12 World Customs Organization (WCO) recommended units | In addition, standardization to more quantity units (43+ units), when reported | Additional measures of quantity
Single weight (net weight in kg) for Merchandise Trade Statistics | In addition, gross weight (net weight plus the weight of the shipping or cargo container), when reported | More information on weight and shipping
Limited quantity estimations for Merchandise Trade Statistics (not all commodities estimated) | Estimation of quantity for all commodities; when applicable. However, some may not be shown for specific commodities | More complete quantity data; especially for aggregated data
Conversion for Merchandise Trade Statistics at 6-digit HS level only | Conversion at any HS level and improved conversion of residuals | More complete converted datasets
Only EBOPS2002 data disseminated for Trade in Services (EBOPS2010 data converted to EBOPS2002) | Trade in Services data also disseminated in EBOPS2010 (when reported in EBOPS2010) | Trade in Services data in both EBOPS2002 and EBOPS2010, when reported

**Comment by jugdemon** [comment]
A quick question, could it be, that the upgrade has rendered comtradr not working? When I make any queries, they always return empty (also on the comtrade.un.org).

**Comment by ChrisMuir** [comment]
Ah, yeah that's interesting, I had no idea the API was down, thank you for bringing it to my attention. I'm not sure what's causing it. It's odd that their online data interface doesn't indicate the service being down or anything like that.

I'll keep my eyes on this, if the outage persist for more than today I will send them a bug report email asking what's going on.

Thanks!

**Comment by jugdemon** [comment]
Good to know that it is not just me. In the meantime I used the manual interface of the worldbank to comtrade to download excel files with the necessary information. Apparently, they still have access (or more likely they run a replica). It looks like a cool package and I will use it the next time I have to access comtrade.

**Comment by ChrisMuir** [comment]
FYI @jugdemon , API is back up and running.

**Comment by wallacemp** [comment]
Hello Chris Muir,

I did not find a specific topic for my question. I would like to know if there is any command in comtradr to use country codes instead of the country names in the ct_search command.

Thank you for understanding

**Comment by ChrisMuir** [comment]
Hello @wallacemp , nope the query function `ct_search()` does not support passing country codes as input. You can, however, create your own wrapper function, like I've demoed below, that will allow you to pass in country codes, and will convert the inputs to their character country names prior to calling `ct_search()`. Be aware, this is a super hacky fix, it uses `comtradr:::get_country_db()`, which is an undocumented non-exported function. Also, there are no checks to ensure the input ints are valid country codes, although you could easily add those checks to the wrapper function below. Hope this is helpful!

```r
ct_search2 <- function(reporters, partners, ...) {
  
  if (!is.character(reporters)) {
    reporters <- as.character(reporters)
  }
  if (!is.character(partners)) {
    partners <- as.character(partners)
  }
  
  country_df <- comtradr:::get_country_db()
  
  reporters <- vapply(reporters, function(x) {
    country_df[country_df$code == x &
                 country_df$reporter == TRUE, ]$country_name
  }, character(1), USE.NAMES = FALSE)
  
  partners <- vapply(partners, function(x) {
    country_df[country_df$code == x &
                 country_df$partner == TRUE, ]$country_name
  }, character(1), USE.NAMES = FALSE)
  
  return(comtradr::ct_search(reporters, partners, ...))
}
```

```r
df <- ct_search2(reporters = 156, 
                 partners = c(276, 288, 392, 484), 
                 trade_direction = "imports", 
                 start_date = 2010, 
                 end_date = 2014)
```
```
dim(df)
#> [1] 20 35
```
The example above is equivalent to doing:
```r
df <- ct_search(reporters = "China", 
                partners = c("Germany", "Ghana", "Japan", "Mexico"), 
                trade_direction = "imports", 
                start_date = 2010, 
                end_date = 2014)
```

**Comment by datapumpernickel** [comment]
Closing this issue, as changes will be adressed in planned relaunch. #45
