### ISSUE TITLE
comtradr is returning an empty data frame

### ISSUE THREAD

**Issue by cindyyawencheng** [ropensci/comtradr#18]
Hi thanks very much for making the package! I have been trying to just go through the examples that you list in your readme file, but unfortunately I've only been getting empty data frames (see an example below).  Do you have any idea what might be going on? If it makes any difference, I'm accessing Comtrade from Germany.  Thanks very much in advance!!

> example1 <- ct_search(reporters = "China", 
                      partners = c("Rep. of Korea", "USA", "Mexico"), 
                       trade_direction = "exports")
> str(example1)
'data.frame':	0 obs. of  35 variables:
 $ classification        : logi 
 $ year                  : logi 
 $ period                : logi 
 $ period_desc           : logi 
 $ aggregate_level       : logi 
 $ is_leaf_code          : logi 
 $ trade_flow_code       : logi 
 $ trade_flow            : logi 
 $ reporter_code         : logi 
 $ reporter              : logi 
 $ reporter_iso          : logi 
 $ partner_code          : logi 
 $ partner               : logi 
 $ partner_iso           : logi 
 $ second_partner_code   : logi 
 $ second_partner        : logi 
 $ second_partner_iso    : logi 
 $ customs_proc_code     : logi 
 $ customs               : logi 
 $ mode_of_transport_code: logi 
 $ mode_of_transport     : logi 
 $ commodity_code        : logi 
 $ commodity             : logi 
 $ qty_unit_code         : logi 
 $ qty_unit              : logi 
 $ alt_qty_unit_code     : logi 
 $ alt_qty_unit          : logi 
 $ qty                   : logi 
 $ alt_qty               : logi 
 $ netweight_kg          : logi 
 $ gross_weight_kg       : logi 
 $ trade_value_usd       : logi 
 $ cif_trade_value_usd   : logi 
 $ fob_trade_value_usd   : logi 
 $ flag                  : logi 
 - attr(*, "url")= chr "https://comtrade.un.org/api/get?max=50000&type=C&freq=A&px=HS&ps=all&r=156&p=410%2C842%2C484&rg=2&cc=TOTAL&fmt=json&head=H"
 - attr(*, "time_stamp")= POSIXct, format: "2018-09-27 16:37:58"
 - attr(*, "req_duration")= num 60.2`

**Comment by ChrisMuir** [comment]
Hi @cindyyawencheng, so the API seems to be down at the moment. I just tried your query on the Comtrade data web interface ([here](https://comtrade.un.org/data/)) and also got zero results. This same thing happened about 20 days ago (see [here](https://github.com/ropensci/comtradr/issues/13#issuecomment-418997055)), and the API service was back up and running within 24 hours. Unfortunately, all we can really do is wait for the service to come back up.

Per user @jugdemon in [this](https://github.com/ropensci/comtradr/issues/13#issuecomment-419216811) comment, there's also access to the Comtrade data via a Worldbank website.

**Comment by cindyyawencheng** [comment]
Ah okay, thanks very much for the quick reply!!
