### ISSUE TITLE
The ct_get_remaining_hourly_queries() can not return the right query limit

### ISSUE THREAD

**Issue by zlfccnu** [ropensci/comtradr#20]
Here is what I want to achieve with `ct_get_remaining_hourly_queries()`:
Since the comtradr API has an hourly query limit for an unauthorized user with just 100 queries per hour, so I'd like to pause the R script until the query limit being reset to 100 again.
Code Version 1:
`for(Year in startYear){## loop on the start year`
  
  `for(country in reporter[,2]){## loop on the report country`
   ` if(ct_get_remaining_hourly_queries()==0){`
      `wait_time=as.numeric((ct_get_reset_time()-Sys.time()))*60+5`
     ` pause(wait_time)`
   ` }`
   ` tryCatch({`
     ` filename=paste0("./rawData/plastic/plastic_",country,"_",Year,".csv")`
     ` if(file.exists(filename)==FALSE){`
       ` assign(paste0("plastic_",country,"_",Year),value = ct_search(reporters =country,partners="All", trade_direction ="all",freq = "annual",start_date =as.character(Year),end_date = as.character(Year+4),commod_codes = comm_code))`
        `write.csv(get(paste0("plastic_",i)),filename)`
      `}`
    `},error=function(e){cat("ERROR:",file=paste0("./rawData/log/plastic_",i,".log"),append = TRUE,conditionMessage(e),"\n")})`
   ` print(country)`
 ` }`
  
`}`
In the first version, I basicly use this chunk of code: `wait_time=as.numeric((ct_get_reset_time()-Sys.time()))*60+5` `pause(wait_time)` . I suppose that the `comtradr` will reset the  `ct_get_remaining_hourly_queries()` to 100 after the R session being paused for a while, but I  get a persistent error from the following `tryCatch` statement：
`ERROR: over the hourly limit. hour resets at 2018-11-08 23:42:35 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 00:42:40 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 01:42:45 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 02:42:50 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 03:42:55 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 04:43:00 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 05:43:05 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 06:43:10 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 07:43:15 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 08:43:20 `
`ERROR: over the hourly limit. hour resets at 2018-11-09 09:43:25 `
So obviously, the query limit has been wrongly estimated  for the current session or IP address.
Thus I modifed my code by introduce the hidden  restart fucntion from rstudio:`.rs.restartR()`. After I manually restart the R session, the ct_get_remaining_hourly_queries() is equal to 100 now.

**Comment by ChrisMuir** [comment]
Just pushed edits that should address this issue. @zlfccnu, your code example should now work without errors.....can you install the latest dev version of this package, then try running your code again?

**Comment by zlfccnu** [comment]
@ChrisMuir Really appreciate your effort. Now it works like a charm!
