### ISSUE TITLE
ct_register_token does not take effect

### ISSUE THREAD

**Issue by zlfccnu** [ropensci/comtradr#21]
I try to register a token by the function `ct_register_token`. However, the download process still hit the 100 query limit. The right query limit after a token be registered should go up to 10,000.

**Comment by pbaine** [comment]
I'm having the same problem, was this issue ever resolved?

**Comment by ChrisMuir** [comment]
Sorry for the delay on this, just pushed a bug fix for this issue. Please try pulling and using the latest dev version from GitHub, let me know if there are still issues.

**Comment by zlfccnu** [comment]
> Sorry for the delay on this, just pushed a bug fix for this issue. Please try pulling and using the latest dev version from GitHub, let me know if there are still issues.

Hi, Chris, the latest version of the pkg now works like a charm. You can close this issue now.
