### ISSUE TITLE
Issue with selection of classification system (px)

### ISSUE THREAD

**Issue by Krisselack** [ropensci/comtradr#23]
Is it possible to select the classification like in the API? I have a list of codes, some are H3 and some are H2. 

In the source code of ct_search  I found the following line, that is used for "px", but I don't get what that does. 

`
code_type <- ct_commodity_db_type() %>% commodity_type_switch
`

**Comment by ChrisMuir** [comment]
Hello Krisselack, are you referring to using different HS codes for commodities? If so, check out function [ct_update_databases](https://github.com/ropensci/comtradr/blob/master/R/ct_update_databases.R), it allows you to download and use any of the available commodity code data sets from the Comtrade website.

If you're referring to something different, please let me know.

**Comment by Zoefish0510** [comment]
Hi, I guess I have a similar issue here. I notice that in v0.0.2 there is an argument codetype in the function [ct_search](https://www.rdocumentation.org/packages/comtradr/versions/0.0.2/topics/ct_search) which allows you to specify which classification you want (HS, SITC and BEC etc). But in v0.2.2 this is no longer available. So is it still possible to specify classification other than HS in ct_search function to get data?

Thanks in advance.

**Comment by ChrisMuir** [comment]
Hi @Zoefish0510 , yes there is a built-in way to specify and utilize any of the commodity classifications that Comtrade uses. Check out the `Package Data` section of the package [vignette](https://cran.r-project.org/web/packages/comtradr/vignettes/comtradr-vignette.html), specifically this paragraph:

`<vignette>`
Additionally, the Comtrade API features a number of different commodity reference tables, based on different trade data classification schemes (for more details, see [this](https://comtrade.un.org/data/doc/api/#DataAvailabilityRequests) page from the API docs). `comtradr` ships with the commodity table for the “Harmonized System”, or “HS”, scheme. The user may download any of the available commodity tables by specifying arg `commodity_type` within function `ct_update_databases` (e.g., `ct_update_databases(commodity_type = "SITC")` will download the commodity table that follows the “Standard International Trade Classification” scheme). Doing this will replace the commodity table on file with the one specified.
`</vignette>`

The function `ct_search()` will always use the commodity classification that currently exists on file.....`HS` is the default, but if you were to run `ct_update_databases(commodity_type = "SITC")` to download the SITC classification, then `ct_search()` would be using SITC.

**Comment by shadishakerin** [comment]
Hello, 

I need to download the data with SITC commodity type, after producing the following:
`
q <- ct_search(reporters = "USA", 
               partners = c("Germany", "France", "Japan", "Mexico"), 
               trade_direction = "imports")
`
So I used the command below for that:
`
ct_update_databases(commodity_type = "SITCrev2") 
`
but I get the following error and my data is not really updated:

Updates found. The following datasets have been downloaded: commodities DB, countries DB
Warning message:
JSON string contains (illegal) UTF8 byte-order-mark! 

Do you have any suggestions? I search this error but did not find something useful for my problem. Also is the a way to download the data in SITC format from the beginning? I could not find a way to change the HS default. 
I would appreciate any help. 

Best, 
Shadi

**Comment by shadishakerin** [comment]
> 
> 
> Hi @Zoefish0510 , yes there is a built-in way to specify and utilize any of the commodity classifications that Comtrade uses. Check out the `Package Data` section of the package [vignette](https://cran.r-project.org/web/packages/comtradr/vignettes/comtradr-vignette.html), specifically this paragraph:
> 
> `<vignette>`
> Additionally, the Comtrade API features a number of different commodity reference tables, based on different trade data classification schemes (for more details, see [this](https://comtrade.un.org/data/doc/api/#DataAvailabilityRequests) page from the API docs). `comtradr` ships with the commodity table for the “Harmonized System”, or “HS”, scheme. The user may download any of the available commodity tables by specifying arg `commodity_type` within function `ct_update_databases` (e.g., `ct_update_databases(commodity_type = "SITC")` will download the commodity table that follows the “Standard International Trade Classification” scheme). Doing this will replace the commodity table on file with the one specified.
> `</vignette>`
> 
> The function `ct_search()` will always use the commodity classification that currently exists on file.....`HS` is the default, but if you were to run `ct_update_databases(commodity_type = "SITC")` to download the SITC classification, then `ct_search()` would be using SITC.

Hello,

I need to download the data with SITC commodity type, after producing the following:
q <- ct_search(reporters = "USA", partners = c("Germany", "France", "Japan", "Mexico"), trade_direction = "imports")
So I used the command below for that:
ct_update_databases(commodity_type = "SITCrev2")
but I get the following error and my data is not really updated:

Updates found. The following datasets have been downloaded: commodities DB, countries DB
Warning message:
JSON string contains (illegal) UTF8 byte-order-mark!

Do you have any suggestions? I search this error but did not find something useful for my problem. Also is the a way to download the data in SITC format from the beginning? I could not find a way to change the HS default.
I would appreciate your help.

Best,
Shadi
