### ISSUE TITLE
COMODO CA cert causing problems for some

### ISSUE THREAD

**Issue by hrbrmstr** [ropensci/comtradr#25]
Saw this <https://community.rstudio.com/t/ssl-certificate-problem-certificate-has-expired/68619> in the RSS feeds and suspected it was the recent COMODO CA cert issue biting them and it is.

https://comtrade.un.org/data/doc/api/ looks fine in-browser b/c browsers are lying to avoid users clamoring for them to "fix it". They can't. Each site has to regen certs.

```r
x <- openssl::download_ssl_cert("comtrade.un.org")

lapply(x, `[[`, "validity")
```

will show (as of this timestamp) that the topmost cert is expired.

Not sure y'all can do anything abt it but I figured I'd toss an issue here in case more folks encounter the situation and go here to note it. They can just pile on to this one :-)

**Comment by ChrisMuir** [comment]
Hi Bob! Thanks a bunch for bringing this to my attention. Ughh, I dealt with this same issue 3 years ago with the UN Comtrade site (and you actually helped me reason through it, on SO). Back then, I sent CRAN a note asking them to archive the package, and contacted the Comtrade team via their "bug report" intake form a few times a week, asking them to consider upgrading their certs. They eventually did. I will start by sending them a few messages inquiring about it, if I don't hear back within a week, I will get in touch with CRAN.

Thanks again for bringing this up Bob. Take care and be safe!

**Comment by edoardochiarotti** [comment]
Hi Chris, it looks like comtrade has updated the certificate and that comtradr works now. It seems it will be valid until December 2020 (you can check here https://www.ionos.com/tools/ssl-checker). Could you confirm this? Have you heard back from comtrade?  Thanks!

**Comment by ChrisMuir** [comment]
Oh this is great, thanks for the heads up! I have not heard from them, but I've been submitting a "bug report" to them every day for the past ~2 weeks, asking them to please update the certs.

It looks like the `COMODO RSA Certification Authority` cert has been updated. It was expiring on 2020-05-30, based on the code snippet that Bob posted in the first post of this issue. Now it's set to expire on 2038-01-18. I will keep this issue open for another week, just to make sure there aren't others that are still experiencing issues.

Thanks!
