### ISSUE TITLE
bug Eswatini  /  Swaziland  

### ISSUE THREAD

**Issue by LaurentSmeets** [ropensci/comtradr#29]
I think the name change of Swaziland  to Eswatini has not yet been properly implemented in either comtradr or the underlying API

This code gives an error
```
ct_search(reporters = "Ghana", 
                   partners = "Eswatini "
                   commod_codes = "all",
                   trade_direction = "exports",
                   start_date = "2018",
                   end_date =  "2018")
  
```

but this code does work

```
ct_search(reporters = "Ghana", 
                   partners = "Swaziland "
                   commod_codes = "all",
                   trade_direction = "exports",
                   start_date = "2018",
                   end_date =  "2018")
  
```

However, in the output Eswatini is mentioned as partner country

first line of output looks like this
````
   classification year period period_desc aggregate_level is_leaf_code trade_flow_code trade_flow reporter_code reporter reporter_iso partner_code  partner partner_iso second_partner_code second_partner
1              H5 2018   2018        2018               2            0               2     Export           288    Ghana          GHA          748 Eswatini         SWZ                  NA           <NA>
````

**Comment by ChrisMuir** [comment]
Hello, thank you for pointing this out. Yes Comtrade updated their countries database. I will push an update to the package data to the main branch today. In the meantime, you can run `comtradr::ct_update_databases()` to have the comtradr package pull down the latest countries database for local use.

**Comment by ChrisMuir** [comment]
Updated the countries pkg data in commit [3dee878](https://github.com/ropensci/comtradr/commit/3dee878ff08b510416230cb61d97ae7b00cfb0b8).
