### ISSUE TITLE
The help docs for parameter combination is not true

### ISSUE THREAD

**Issue by zlfccnu** [ropensci/comtradr#32]
When I try to download the data with a registered token, the actual valid parameter combination `reporters`, `partners` and `date range` accept at most 2 `All`s. check the code below:
`ct_search(reporters ="China",partners="All", trade_direction ="all",freq = "annual",start_date ="all",end_date = "all",commod_codes = "01")`

However, as stated in the docs: 
> Between params "reporters", "partners", and the query date range (as dictated by the two params "start_date" and "end_date"), only one of these three may use the catch-all input "All".

I think there might be some inconsistency.

**Comment by ChrisMuir** [comment]
Hello, I actually don't have access to a valid API token. When I run your example query, I get this error resp:

```
Error: API request failed. Err msg from Comtrade:
  All years may only be selected if both reporters and partners are not set to 'all'.
```

I plugged the query into the Comtrade search UI/website, and I get the same error response.

The Comtrade [API docs](https://comtrade.un.org/Data/Doc/API) still indicate that only one of those fields may use the `"all"` value (see section `Usage limits` in the docs).

Are you able to use the `"all"` value in two of those fields, with a valid API token?

**Comment by datapumpernickel** [comment]
Closing this issue, as changes in the API will mean we will update the documentation. See #45
