### ISSUE TITLE
Dowloading bulk data with SITC commodity type from using comtradr package

### ISSUE THREAD

**Issue by shadishakerin** [ropensci/comtradr#35]
Dear all, 

I have been working on downloading bulk data using comtradr package and I'm facing several problems. My goal is to download commodity data for all commodities, all countries and all time periods, I work with a data download permission/IP that is supposed to let me download all the three variables set at "all". But I still get the error: _between 'reporters', 'partners', and date range, only one of these may be 'all'_
Could someone tell me what mistake I am making here?

Another problem is that I would need the SITC commodity types which are not the default for downloading with ct_search() command. The suggested solution is to covert or in other words update the data by ct_update_databases() command and specify px = S2. Below are the code that I used:

`q <- ct_search(reporters = "all", 
               partners = "all", 
               trade_direction = "all")`

and to update the category:

`ct_update_databases(commodity_type = "SITCrev2")`
I would highly appreciate your help. 
Best, 
Shadi

**Comment by datapumpernickel** [comment]
Closing this issue, as the comprehensive relaunch of the API means this function will most likely be deprecated. Please see #45 for details.
