### ISSUE TITLE
"remaining hourly queries" is not resetting at "reset time"

### ISSUE THREAD

**Issue by rcalence** [ropensci/comtradr#36]
I have more queries to run than the API permits in an hour, so I am breaking them up into batches and trying to run them on hourly (plus a few minutes cushion) intervals. When I try to run the second batch (after the "reset time"), the "reset time" resets but not "remaining hourly queries." So if I drove the queries down to zero in the previous hour, `ct_get_remaining_hourly_queries()` continues to return zero after the "reset time" (indefinitely, as far as I can tell) -- and the second batch of queries fails with "Error: over the hourly limit." As a workaround, I can detach/unload and then reattach comtradr between batches -- which I assume is clearing the cache values (but is also evading comtradr's intended controls on how many queries are sent to the API hourly.)

**Comment by ChrisMuir** [comment]
Hey, I'm not able to replicate this. I tried running the hourly queries down to zero, checking the reset time using `get("next_hour_reset", envir = ct_env)`, and coming back after that time had passed. At that point, `ct_get_remaining_hourly_queries()` was returning `100` for me.

Can you share the code that you're running, and I can try running it locally?

**Comment by datapumpernickel** [comment]
Closing this issue, as changes in the API will mean that this function will most likely be deprecated. See #45
