### ISSUE TITLE
`ct_search()` unable to loop over list of product codes

### ISSUE THREAD

**Issue by wreesman** [ropensci/comtradr#38]
I need to pull import and export data between the US, China, and the World over a span of 5 years for a list of approx. 1,500 HS6 codes. I have an authentication token that I've successfully passed via `ct_register_token()` so theoretically I should be able to make 1,500 separate pulls from the API without hitting the rate limit. What I am attempting, then, is this:

```
trade <- lapply(hs1, function(i){
                                Sys.sleep(1)
                                tmp <- ct_search(reporters = "USA", partners = c("China", "World"),
                                                 trade_direction = c("imports", "exports"), start_date = 2000,
                                                 end_date = 2004, commod_codes = i)
                                df <- as.data.frame(do.call(rbind, tmp))
                                return(df)
})
```
where `hs1` is a list ~1,500 elements long. However, every single time I run this, I get this error: `Error: Comtrade API request failed, with status code [500]`. Is this a bug with the package, or a problem with the API itself? Am I just trying to pull too much/too often, despite the token? Should I be trying to loop these pulls in a different manner? Or perhaps the authentication token not passing to the API correctly, so it thinks I've exceeded my rate limit? (when I check `ct_get_remaining_queries()`, it is still well in the 9 thousands after I tried running the `lapply` above several times). 

An option that works for what I want is using the get.Comtrade function [here](https://comtrade.un.org/Data/Doc/api/ex/r), chunking the list of HS codes into lists of 100, and looping the lapply over those chunks, waiting 1 hour in between (since I can't figure out how to pass the authentication token within the function above). This is fine and works, but it takes 15 hours to get the data I want, and I'd like to see if there's a quicker way that utilizes the fact I have a token. Thanks in advance for any assistance in this regard.

**Comment by amannj** [comment]
Hi,

Unfortunately, I haven't had time to look into what I referred to as "issue 2" in #34 (that is, we still run into guest-user restrictions), but I have a strong suspicion that this is what's going on:

> Could you check, when exactly `ct_search()` starts throwing these error messages? If it is at `i = 100+`, that is, once you have exceeded the guest user limit, then I think these issues might be related.

For now, a (quicker) solution would probably be to simply use comtrade's [Data_GetBulk](https://comtrade.un.org/api/swagger/ui/index#!/Data/Data_GetBulk) service, where you specify the API parameters accordingly (see [here](https://comtrade.un.org/data/doc/api/bulk)).

**Comment by datapumpernickel** [comment]
Closing this issue, as the comprehensive relaunch of the API means most functions that have this upper limit are deprecated. Please see #45 for details.
