### ISSUE TITLE
ct_get_remaining_hourly_queries() does not get updated after validating token

### ISSUE THREAD

**Issue by krystaltkh** [ropensci/comtradr#39]
I have tried the potential solution suggested in #34 , but I face a slightly different issue. My token is authenticated (verified at https://comtrade.un.org/ws/CheckRights.aspx). The remaining hourly queries does not get updated in the ct_get_remaining_hourly_queries( ) function, but is updated in getOption("comtradr"). Unfortunately, I have been limited to the standard access despite having the token.

```
> ct_register_token(goodtoken)
```
```
> getOption("comtradr")
$comtrade
$comtrade$token
[1] goodtoken

$comtrade$account_type
[1] "premium"

$comtrade$per_hour_limit
[1] 10000

$comtrade$per_second_limit
[1] 1


attr(,"class")
[1] "comtradr_credentials"
```
```
> ct_get_remaining_hourly_queries()
[1] 100
```

**Comment by datapumpernickel** [comment]
Closing this issue, as the comprehensive relaunch of the API means these functions will most likely be deprecated. Please see #45 for details.
