### ISSUE TITLE
RStudio - error Error in curl::handle_setopt(handle, .list = req$options) :    Unknown options: curlopt_ssl_verifypeer, set.ssl.primary.verifypeer

### ISSUE THREAD

**Issue by borowiej** [ropensci/comtradr#41]
Hello, 

I am trying to download data from the UN Comtrade database. After updating my RStudio I have the same problem either using the ct_search function in the comtradr package or using get.Comtrade function define on this website: http://nathanlane.info/2017/04/19/uncomtrade.html . There is an error: Error in curl::handle_setopt(handle, .list = req$options) : 
Unknown options: curlopt_ssl_verifypeer, set.ssl.primary.verifypeer

Can anyone resolve this problem and suggest to me what should I do?

**Comment by datapumpernickel** [comment]
Closing this issue, as the comprehensive relaunch of the API means this function will most likely be deprecated. Please see #45 for details.
