### ISSUE TITLE
Error Message Maximum resultset is: 10000

### ISSUE THREAD

**Issue by rachel-pompa** [ropensci/comtradr#42]
I am attempting to pull UN Comtrade data using the r comtrade package with a nested for loop for multiple trading partners and years. The code will iterate several times and then stops with the following error

Error: API request failed. Err msg from Comtrade:
  Maximum resultset is: 10000

Does this error message suggest there is something wrong with my query or that I have hit some sort of limit? I know that I have not hit the 100 query limit for the hour, so this is something else.

**Comment by datapumpernickel** [comment]
Closing this issue, as the comprehensive relaunch of the API means most functions that have this upper limit are deprecated. Please see #45 for details.
