### ISSUE TITLE
API will be decommissioned by 2023

### ISSUE THREAD

**Issue by datapumpernickel** [ropensci/comtradr#43]
Hi all,

thanks for the great package, has saved me tremendous amounts of time in the past. 
I am writing, because to my understanding, the current API will be decommissioned by 2023. 
See here: https://unstats.un.org/wiki/display/comtrade/New+Comtrade+FAQ+for+Advanced+Users#NewComtradeFAQforAdvancedUsers-WhatisthelegacyoftheUNComtrade?UntilwhencanIuseit? 

I find this quite worrying, while tinkering around with the new API, I have found it to be quite unstable. Some reported codes are not in the references, others are in the references, but do not work anymore (such as "all"). 

As I see it, this package might be obsolete, unless you already are a registered user. 
I was wondering, whether: 
1) Somebody has tried adapting the package to the new comtrade or is planning to do that? As far as I can see, quite some things have changed, most importantly the authentication and this would require substantial investment of time, right? 

2) Somebody would be willing to let the UN know that maybe they could postpone the decomissioning until the new version is fully up and running? I am not sure, whether the preoblems I am having are just because I am unable to propperly query, or whether it really is a bit difficult to understand. 

Thanks and all the best!

**Comment by ASEIITO** [comment]
Hi! I also share this concern. I found a new description as "This page and associated data API will be discontinued at the end of Q1 2023" on the old version website as below. According this announcement, I guess the the comtradr package will stop working at the end of March 2023.

![image](https://user-images.githubusercontent.com/63130024/211218050-118d4e14-2ef7-4754-97e6-4b7d49277823.png)
https://comtrade.un.org/data (Accessed 8 January 2023)

**Comment by b14-RSA** [comment]
Hi, has anyone got an update or idea if the comtradr package will be updated or will stop working this month? I am having difficulty with existing code (that worked in the past) and was wondering if it has to do with this API being discontinued. Any info will be appreciated.

**Comment by weizhang18** [comment]
The package no longer works. Hope you can make it working again please.

A part of my dashboard depends on it. 

`> update.packages("comtradr")
> library(comtradr)
> q <- ct_search(reporters = "USA", 
+                partners = c("Germany", "France", "Japan", "Mexico"), 
+                trade_direction = "imports")
Error: API request failed. Err msg from Comtrade:
  Access to legacy API is only allowed to premium users. Please visit https://comtradeplus.un.org to get free access.`

**Comment by datapumpernickel** [comment]
Ok, since nobody from the original maintainers seems to be active, I hacked together a little wrapper for the new Comtrade API today. 
It works for me, but it still lacks a lot of documentation and tests to ensure proper functioning. Also there is no version that properly works without an API key, so in any case you will have to sign up for the website. With the proper key you should be able to get most data from my package here though: 

https://github.com/datapumpernickel/untrader

**Comment by ChrisMuir** [comment]
Hey all, I'm the author and maintainer of comtradr. I started looking into package updates to make it compatible with the latest UN API last weekend, but did not get very far. I honestly longer have the appetite to continue maintaining this package, I just sent a email to rOpenSci letting them know. I will either update here, or start a new Issue to track what will be happening with this package in the near future.

I'm sorry to everyone.

**Comment by b14-RSA** [comment]
@datapumpernickel I am very happy to see your package in development. Thank you. I will have a look at it this evening (RSA time). I am not a very advanced R user so I am not sure how much help I can contribute but if I spot anything that I don't understand/that doesn't work I can contribute in that way by letting you know? Or I can learn !

**Comment by datapumpernickel** [comment]
@b14-RSA Thank you, that would be very helpful. I am sure there must be dozens of bugs in there still! :D

**Comment by ChrisMuir** [comment]
Hey all, I'm officially looking for a new maintainer:  https://github.com/ropensci/comtradr/issues/44

@datapumpernickel I know you started your own package to work with the UN's updated API. If you'd prefer to take over comtradr, let me know!

**Comment by datapumpernickel** [comment]
Hi @ChrisMuir, sad to see you go. I think we can probably close this issue and move the discussion to the maintainer-issue #44?

**Comment by pachadotdev** [comment]
@maelle Hi!
I've worked with international trade data since 2015, and I've followed the changes to UN COMTRADE closely. How can I contribute?
As an example, I've maintained https://shiny.tradestatistics.io/countryprofiles/ for years now, and also the tradestatistics package, which is a part of rOpenSci.

**Comment by maelle** [comment]
:wave: @pachadotdev, thanks for volunteering, but there are quite a few volunteers in #44 already and as previously discussed we aim to not overburden volunteers. :slightly_smiling_face:

**Comment by pachadotdev** [comment]
> wave @pachadotdev, thanks for volunteering, but there are quite a few volunteers in #44 already and as previously discussed we aim to not overburden volunteers. slightly_smiling_face

sure! not maintain, but to contribute with functions, I have a few functions that run with the new API
I've been using classic COMTRADE for almost 10 yrs, glad I'm not a 1-trick pony or I'd be in trouble with this change

**Comment by datapumpernickel** [comment]
Closing, as the discussion has moved over to #44.
