### ISSUE TITLE
Add a "depreciated" error to legacy functions

### ISSUE THREAD

**Issue by hgoers** [ropensci/comtradr#47]
We need to provide informative depreciation errors to the existing functions. I propose that we use [`lifecycle`](https://lifecycle.r-lib.org/) to do this. In the depreciated error we should point the user to the new, relevant function and its documentation.

**Comment by datapumpernickel** [comment]
done in #48
However, still needs to be updated with the proper reference to the new functions, once we have them all ready.

**Comment by datapumpernickel** [comment]
Fixed in https://github.com/ropensci/comtradr/commit/57e2d643f8c631d55b8a441c01d064b3771301b6 and following.
