### ISSUE TITLE
Verify possible values for the frequency arg

### ISSUE THREAD

**Issue by hgoers** [ropensci/comtradr#49]
Currently, we accept A and M. However, the previous API allowed you to pull quarterly data (Q). Need to verify whether this is still possible following the update.

**Comment by datapumpernickel** [comment]
In the documentation it only specifies A and M
<img width="535" alt="Screenshot Comtrade" src="https://github.com/ropensci/comtradr/assets/65470117/fa1b63d9-b0d1-4165-858f-351e7259e6a0">
