### ISSUE TITLE
Extend possible values for the commodity_classification arg

### ISSUE THREAD

**Issue by hgoers** [ropensci/comtradr#50]
Currently only accept HS. Need to update to include SITC, BEC or EBOPS.

**Comment by datapumpernickel** [comment]
this touches on #52, function `ct_get_commodity_tables` (could be an internal helper function only) takes valid comtrade parameters for the product classification and returns the reference tables to include for validation

**Comment by datapumpernickel** [comment]
this in theory implemented.

**Comment by datapumpernickel** [comment]
This seems to be implemented on the Comtrade site with a check for the size of the URL request and caps at 4,096 characters. We check for this now too: https://github.com/ropensci/comtradr/commit/1a28183a6f4c76aa75527c8cbe9d80549d728950
