### ISSUE TITLE
Provide an argument that allows users to pull all countries and country groupings

### ISSUE THREAD

**Issue by hgoers** [ropensci/comtradr#51]
Currently, 'all' reporters or partners excludes groupings such as ASEAN or the EU. We should provide users with a means of pulling data for these groupings.

**Comment by datapumpernickel** [comment]
I have implemented the behavior of the original API, that when a NULL value is provided, e.g. the parameter is missing from the API call, all possible values are returned. This allows to also return groupings. 
Hence, i am closing for now. Please reopen if needed!
