### ISSUE TITLE
write test suite

### ISSUE THREAD

**Issue by datapumpernickel** [ropensci/comtradr#58]
We need a proper test suite for the package as a whole. A first start is done in the following commit https://github.com/ropensci/comtradr/commit/529bb516b69590c359e63ac644f838e6056ee02a. It still only achieves about 70% coverage and I think some important checks on the constructed URL is missing. FYI @pachadotdev

**Comment by pachadotdev** [comment]
amazing! we have a lot of overlap, let me fix that and I'll complete the other 30%

**Comment by datapumpernickel** [comment]
Closing, as we have about 79% coverage for now and the remaining functions cannot be tested as easily, as it involves very large API calls (over 250k rows) that would be too large to store as internal data to the package.
