### ISSUE TITLE
SITC codes are not working properly

### ISSUE THREAD

**Issue by pedrocarsamar** [ropensci/comtradr#78]
Hello there

I am a SITC Revision 3 code user and I just noticed that S3 classification is not working properly in the function ct_get_data(). When I set "S3" argument (in commodity classification), it will return data for the commodity codes I want, but its range is limited to 2009. So, I can't get data past 2009 using S3 classification. 

For example, suppose I try to run:

`ct_get_data(
    reporter = 'all',
    flow_direction = c('import', 'export'),
    partner = 'World',
    frequency = 'A',
    start_date = 2010,
    end_date = 2011,
    commodity_classification = 'S3',
    commodity_code = c('2631', '21', '29195')`

It will return a dataframe with nothing.

Eventually I'll need to convert all my S3 codes to HS in order to do my work. But I just wanted you to know that there is a problem with S3 classification.

Best regards

**Comment by datapumpernickel** [comment]
Hi Pedro (if I may),

thanks for informing about this. It is not actually an issue with the package, but in the new API, S3 codes are only available up to 2009. You may want to use S4 codes, to get data from 2007 onwards. 

See here for reference: https://unstats.un.org/wiki/display/comtrade/New+Comtrade+FAQ+for+Advanced+Users?preview=/135004494/135004492/Picture1.png 

Unless there is another issue with the package I would close this issue as "solved", although it unfortunately does not help you much with the S3 classification. 

Best
Paul
